name: Auto Merge Development to Staging
on:
  pull_request:
    branches: [development]
    types: [closed]

jobs:
  merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Merge development into staging
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin dev staging
          git checkout staging
          git merge --no-ff development -m "Auto-merge development into staging"
          git push origin staging
