name: Rebase development onto main

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  rebase:
    runs-on: ubuntu-latest
    if: github.actor == 'Willxones' 
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Rebase development onto main
        run: |
          git checkout development
          git pull origin development
          git rebase main || (echo "Merge failed: Please resolve conflicts manually" && exit 1)

      - name: Push rebased development to main
        run: |
          git checkout main
          git reset --hard development  # Move main to the new rebased history
          git push origin main --force
